
name: deploy

on:
  push:
    paths:
      - apps/server/*
      - libs/*
    tags:
      - "v*"

jobs:
  deploy:
    name: deploy
    runs-on: macos-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.14.2
          cache: npm

      - name: Get version
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm run bootstrap

      - name: Build Packages
        run: npm run build

      - name: Build Site
        run: npm run build:site
        
        
