
name: Deploy

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
  

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.14.2

      - name: Get version
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Npm Version
        run: npm install npm@8.19.3 -g

      - name: Npm Version
        run: npm --version

      - name: Install
        run: npm run bootstrap

      - name: Build Tool
        run: npm run build:tool

      - name: Packages link
        run: npm run link

      - name: Build hooks
        run: npm run build:hooks

      - name: Build ui
        run: npm run build:ui

      - name: Build Site
        run: npm run build:site

      - name: Setup Pages
        uses: actions/configure-pages@v1
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
