
name: Deploy

on:
  push:
    tags:
      - "v*"
  

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.14.2

      - name: Get version
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Npm Version
        run: npm install npm@8.19.3 -g

      - name: Npm Version
        run: npm --version

      - name: Packages link
        run: npm run link

      - name: Install
        run: npm run bootstrap

      - name: Build Packages
        run: npm run build

      - name: Build Site
        run: npm run build:site
        
        
