
name: Deploy

on:
  push:
    tags:
      - "v*"
    branches:
      - development
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
  

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.14.2

      - name: Get version
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Upgrade Version
        run: npm install npm@8.19.3 -g

      - name: Npm Version
        run: npm --version

      - name: Cache Node_modules
        uses: actions/cache@v3
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm run bootstrap

      - name: Build 
        run: npm run build

      - name: Test
        run: npm run test

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.14.2

      - name: Get version
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Upgrade Version
        run: npm install npm@8.19.3 -g

      - name: Npm Version
        run: npm --version

      - name: Gatsby Cache Folder
        uses: actions/cache@v3
        with:
          key: 'gatsby-cache-folder'
          path: .cache

      - name: Cache Node_modules
        uses: actions/cache@v3
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm run bootstrap

      - name: Build 
        run: npm run build

      - name: Build Site
        run: npm run build:site

      - name: Setup Pages
        uses: actions/configure-pages@v1
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
